# Site settings
title: selivan.github.io
#email: selivan.at.github@gmail.com
# > this means to ignore newlines until "baseurl:"
description: >
  Just another IT blog
# the subpath of your site, e.g. /blog
baseurl: ""
# the base hostname & protocol for your site
url: "https://selivan.github.io"
#twitter_username: i_got_no_twitter
github_username: selivan

# Specify social profiles in site metadata with jekyll-seo-tag plugin
# https://jekyll.github.io/jekyll-seo-tag/usage/
# https://developers.google.com/search/docs/data-types/social-profile
social:
  name: Pavel Selivanov
  links:
    - https://github.com/selivan/
    - https://www.linkedin.com/in/pavel-selivanov-9b8398ba/

# Publish posts with a future date
# Solves problem with posting posts from timezone with positive offset to UTC
future: true

# https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors
highlighter: rouge
markdown: kramdown
# Use Github Flavored Markdown
kramdown:
   input: GFM
timezone: Europe/Moscow
# https://help.github.com/articles/configuring-jekyll-plugins/
plugins:
  # RSS feeds
  - jekyll-feed
  # https://help.github.com/articles/redirects-on-github-pages/
  # Google Bot treats <link rel=canonical href=...> as 301 redirect: https://stackoverflow.com/a/19717455/890863
  # Example:
  # redirect_from: "/foo"
  - jekyll-redirect-from
  # GitHub Emoji https://help.github.com/articles/emoji-on-github-pages/
  # Example: :+1:
  - jemoji
  # GitHub @mentions https://help.github.com/articles/mentions-on-github-pages/
  # Example: @username
  - jekyll-mentions
  # Jekyll-seo-tag: add metadata tags for search engines and social networks to better index and display site's content
  # https://github.com/jekyll/jekyll-seo-tag#usage
  - jekyll-seo-tag
  # Speedup: cache the rendering of Liquid includes
  # https://github.com/benbalter/jekyll-include-cache
  # ERROR: localy installed github-pages doesn't like this plugin
  #- jekyll-include-cache
  # GitHub Sitemap - generate /sitemap.xml for search engines
  # https://help.github.com/articles/sitemaps-for-github-pages/
  # Should be listed last to include content generated by other plugins
  - jekyll-sitemap

# Exclude files and directories from jekyll conversion
exclude: [TODO.md]
